# Site settings
baseURL = "https://erkka-salo-portfolio.netlify.app/"
languageCode = "en-us"
title = "Erkka"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Erkka Salo"
  description = "I am an ambitious masters student at London Business School. I am fond fan of diversity, meeting new people and sports. This website is to showcase some of my analyses conducted with R"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Let's get in touch!"
    text = "Email: esalo.MFA2021@london.edu, Tel: +358401690787"

  # Navigation Section
  [params.navigation]
    title = "Erkka Salo"
    subtitle = "website portfolio"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About me"
      url = "aboutme/aboutme"

    [[params.navigation.links]]
      name = "My lifestyle"
      url = "health/health"

    [[params.navigation.links]]
      name = "Projects"
      url = "projects"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Snapshots into my life"
      url = "blogs"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Welcome, my name is Erkka. I wish you enjoy my personalized website!"
    subtitle = "This is my portfolio website"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "About me"
      subtitle = "Introduction - Erkka Salo"
      image = "me.jpg"
      url = "aboutme/aboutme"

    [[params.tiles.showcase]]
      title = "Lifestyle"
      subtitle = "Healthy routines"
      image = "health.jpg"
      url = "health/health"

    [[params.tiles.showcase]]
      title = "Gaining while acting green?"
      subtitle = "Academic Research"
      image = "thesis.jpg"
      url = "projects/thesis"

    [[params.tiles.showcase]]
      title = "Covid-19"
      subtitle = "Insights into the pandemic"
      image = "covid.jpg"
      url = "projects/covid"

    [[params.tiles.showcase]]
      title = "2016 US elections"
      subtitle = "Top cities and candidates by contributions"
      image = "elections.jpg"
      url = "projects/elections"

    [[params.tiles.showcase]]
      title = "Yield curve analysis"
      subtitle = "current low rate environment"
      image = "yield.jpg"
      url = "projects/yield"
    # You can make more showcases by copy and pasting the code above

[[params.footer.social]]
      icon = "fa-envelope"
      url= "esalo.mfa2021@london.edu"
      label = "Email"

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Snapshots on my leisure time"
    subtitle = "Random pictures"
    buttonText = "Discover!"
    url = "blogs"


  # Contact section
  #[params.contact]
   # enable = true
    #buttonSend = "Send message"
    #buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "esalo.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+358401690787"

    [[params.contact.address]]
    title = "Address"
    street = "Marylebone"
    city = "London, NW1 5NY"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "London Business School"

    # Uses font awesome icons
   
    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/erkka.salo.9/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/eesalo/?hl=sv"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/Saloerkka"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/ejsalo/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
